# Defines the used language and the corresponding file used. The corresponding language file will be placed next to the config.yml named: <Language>.yml
Language: en
# Options:
#     Overwrite (deletes all changes from the file and extracts a new language file)
#     Upgrade (extracts a new language file and copy's all settings from the old language file)
#     Update (adds the default (english) text values for all missing values, just some basic formatting)
UpdateMode: Upgrade


# When auto update is disabled you still can use the build in update function manually with /marry update
AutoUpdate: true

# Config File Version. Don't touch it!
Version: 1