name: "${project.name}"
author: "${author}"
website: "${project.url}"
main: "${mainClass}"
description: "${project.description}"
version: "${version}"
api-version: "1.13"

depend: [ WorldGuard, PCGF_PluginLib ]

permissions:
  wgblockrestricter.ignore:
    default: op