name: ${project.name}
main: com.mewin.WGBlockRestricter.WGBlockRestricterPlugin
description: ${project.description}
version: ${project.version}
authors: [ GeorgH93, mewin ]
depend: [ WorldGuard ]

permissions:
  wgblockrestricter.ignore:
    default: op